# Generated by Django 4.0.1 on 2022-02-17 22:30

import blogUsers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogUsers', '0003_alter_profile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=blogUsers.models.path_file_name),
        ),
    ]
