# Generated by Django 4.0.1 on 2022-02-18 14:14

import blogUsers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogUsers', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/profile/user.png', null=True, upload_to=blogUsers.models.path_file_name),
        ),
    ]
