# Generated by Django 4.0.1 on 2022-02-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogUsers', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
