# Generated by Django 4.0.1 on 2022-02-17 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='liked_by',
            field=models.ManyToManyField(related_name='post_likedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
