# Generated by Django 4.0.1 on 2022-02-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blogpost_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comments',
            field=models.ManyToManyField(related_name='blog_comments', to='Blog.Comment'),
        ),
    ]
