# Generated by Django 4.0.1 on 2022-02-17 22:25

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blogpost_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to=Blog.models.path_file_name),
        ),
    ]
