# Generated by Django 4.0.1 on 2022-02-18 14:14

import Blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0006_blogpost_comments_by_remove_blogpost_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='comments_by',
            field=models.ManyToManyField(blank=True, related_name='blog_comments', to='Blog.Comment'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=Blog.models.path_file_name),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='post_likedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
