# Generated by Django 4.0.1 on 2022-02-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_blogpost_comments_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='caption',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
