# Generated by Django 4.0.1 on 2022-02-21 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0012_alter_bookmark_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='blogPost',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='blogPost',
            field=models.ManyToManyField(related_name='bookmark_post', to='Blog.BlogPost'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
