# Generated by Django 4.0.1 on 2022-02-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_remove_bookmark_blogpost_bookmark_blogpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='blogPost',
            field=models.ManyToManyField(blank=True, related_name='bookmark_post', to='Blog.BlogPost'),
        ),
    ]
