# Generated by Django 4.0.1 on 2022-02-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_alter_bookmark_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
    ]
