# Generated by Django 4.0.1 on 2022-02-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_blogpost_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='suggested_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggest', to='Blog.topic'),
        ),
    ]
