# Generated by Django 4.0.1 on 2022-03-30 12:38

import Blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0017_alter_blogpost_blog_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='view_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Blog.models.path_file_name_topic),
        ),
    ]
